# Generated by Django 4.1.7 on 2023-04-27 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_userrole_delete_maintcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='userRole',
        ),
        migrations.AddField(
            model_name='userrole',
            name='roleStatus',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
