# Generated by Django 4.2 on 2023-04-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(default='L', max_length=15)),
                ('buildingName', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('S', 'Solved'), ('U', 'Unsolved'), ('P', 'Pending'), ('O', 'Open')], default='U', max_length=15)),
                ('description', models.TextField(max_length=255)),
                ('problemType', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
