# Generated by Django 4.2 on 2023-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0003_remove_ticket_image_remove_ticket_problemtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
