# Generated by Django 4.2 on 2023-05-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0007_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
