# Generated by Django 4.2 on 2023-05-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0009_alter_ticket_issue_alter_ticket_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
