# Generated by Django 4.2 on 2023-05-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0010_alter_ticket_issue_alter_ticket_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.CharField(default='', max_length=15),
        ),
    ]
